### ISSUE TITLE
Disease Analyzer assigning identical labels to identified Samples.

### ISSUE THREAD

**Issue by Spacecommodore** [PolarisSS13/Custom-Items#184]
When using the disease analyzer to identify new strains of viruses, it will assign it an identical label. 

![Disease analyzer 1](https://user-images.githubusercontent.com/44623327/218635178-6c9ea327-c07a-4ccd-904c-6f5dd0ffb1b2.PNG)
![Disease analyzer 2](https://user-images.githubusercontent.com/44623327/218635172-fcc9c919-f2a2-4dda-9513-b825b45580b0.PNG)
![Disease Analyzer 3](https://user-images.githubusercontent.com/44623327/218635180-26fb9559-7b84-40aa-ba5c-c6461fbf4e23.PNG)

**Comment by Atermonera** [comment]
This... is the custom items repo. You should open this in the `Polaris` repo.
